-- Auto-generated from 5SIM guest prices.
-- Generated at: 2026-04-10T08:58:14Z
USE `toolboxnova`;

INSERT INTO `sms_country` (`name`, `display_name`, `iso2`, `flag`) VALUES
('afghanistan', 'Afghanistan', 'AF', '🇦🇫'),
('albania', 'Albania', 'AL', '🇦🇱'),
('algeria', 'Algeria', 'DZ', '🇩🇿'),
('angola', 'Angola', 'AO', '🇦🇴'),
('antiguaandbarbuda', 'Antigua & Barbuda', 'AG', '🇦🇬'),
('argentina', 'Argentina', 'AR', '🇦🇷'),
('armenia', 'Armenia', 'AM', '🇦🇲'),
('aruba', 'Aruba', 'AW', '🇦🇼'),
('australia', 'Australia', 'AU', '🇦🇺'),
('austria', 'Austria', 'AT', '🇦🇹'),
('azerbaijan', 'Azerbaijan', 'AZ', '🇦🇿'),
('bahamas', 'Bahamas', 'BS', '🇧🇸'),
('bahrain', 'Bahrain', 'BH', '🇧🇭'),
('bangladesh', 'Bangladesh', 'BD', '🇧🇩'),
('barbados', 'Barbados', 'BB', '🇧🇧'),
('belarus', 'Belarus', 'BY', '🇧🇾'),
('belgium', 'Belgium', 'BE', '🇧🇪'),
('belize', 'Belize', 'BZ', '🇧🇿'),
('benin', 'Benin', 'BJ', '🇧🇯'),
('bhutane', 'Bhutan', 'BT', '🇧🇹'),
('bih', 'Bosnia & Herzegovina', 'BA', '🇧🇦'),
('bolivia', 'Bolivia', 'BO', '🇧🇴'),
('botswana', 'Botswana', 'BW', '🇧🇼'),
('brazil', 'Brazil', 'BR', '🇧🇷'),
('bulgaria', 'Bulgaria', 'BG', '🇧🇬'),
('burkinafaso', 'Burkina Faso', 'BF', '🇧🇫'),
('burundi', 'Burundi', 'BI', '🇧🇮'),
('cambodia', 'Cambodia', 'KH', '🇰🇭'),
('cameroon', 'Cameroon', 'CM', '🇨🇲'),
('canada', 'Canada', 'CA', '🇨🇦'),
('capeverde', 'Cape Verde', 'CV', '🇨🇻'),
('chad', 'Chad', 'TD', '🇹🇩'),
('chile', 'Chile', 'CL', '🇨🇱'),
('colombia', 'Colombia', 'CO', '🇨🇴'),
('comoros', 'Comoros', 'KM', '🇰🇲'),
('congo', 'Congo', 'CG', '🇨🇬'),
('costarica', 'Costa Rica', 'CR', '🇨🇷'),
('croatia', 'Croatia', 'HR', '🇭🇷'),
('cyprus', 'Cyprus', 'CY', '🇨🇾'),
('czech', 'Czech Republic', 'CZ', '🇨🇿'),
('denmark', 'Denmark', 'DK', '🇩🇰'),
('djibouti', 'Djibouti', 'DJ', '🇩🇯'),
('dominicana', 'Dominican Republic', 'DO', '🇩🇴'),
('easttimor', 'East Timor', 'TL', '🇹🇱'),
('ecuador', 'Ecuador', 'EC', '🇪🇨'),
('egypt', 'Egypt', 'EG', '🇪🇬'),
('england', 'United Kingdom', 'GB', '🇬🇧'),
('equatorialguinea', 'Equatorial Guinea', 'GQ', '🇬🇶'),
('estonia', 'Estonia', 'EE', '🇪🇪'),
('ethiopia', 'Ethiopia', 'ET', '🇪🇹'),
('finland', 'Finland', 'FI', '🇫🇮'),
('france', 'France', 'FR', '🇫🇷'),
('frenchguiana', 'French Guiana', 'GF', '🇬🇫'),
('gabon', 'Gabon', 'GA', '🇬🇦'),
('gambia', 'Gambia', 'GM', '🇬🇲'),
('georgia', 'Georgia', 'GE', '🇬🇪'),
('germany', 'Germany', 'DE', '🇩🇪'),
('ghana', 'Ghana', 'GH', '🇬🇭'),
('greece', 'Greece', 'GR', '🇬🇷'),
('guadeloupe', 'Guadeloupe', 'GP', '🇬🇵'),
('guatemala', 'Guatemala', 'GT', '🇬🇹'),
('guinea', 'Guinea', 'GN', '🇬🇳'),
('guineabissau', 'Guinea-Bissau', 'GW', '🇬🇼'),
('guyana', 'Guyana', 'GY', '🇬🇾'),
('haiti', 'Haiti', 'HT', '🇭🇹'),
('honduras', 'Honduras', 'HN', '🇭🇳'),
('hongkong', 'Hong Kong', 'HK', '🇭🇰'),
('hungary', 'Hungary', 'HU', '🇭🇺'),
('india', 'India', 'IN', '🇮🇳'),
('indonesia', 'Indonesia', 'ID', '🇮🇩'),
('ireland', 'Ireland', 'IE', '🇮🇪'),
('israel', 'Israel', 'IL', '🇮🇱'),
('italy', 'Italy', 'IT', '🇮🇹'),
('ivorycoast', 'Ivory Coast', 'CI', '🇨🇮'),
('jamaica', 'Jamaica', 'JM', '🇯🇲'),
('jordan', 'Jordan', 'JO', '🇯🇴'),
('kazakhstan', 'Kazakhstan', 'KZ', '🇰🇿'),
('kenya', 'Kenya', 'KE', '🇰🇪'),
('kuwait', 'Kuwait', 'KW', '🇰🇼'),
('kyrgyzstan', 'Kyrgyzstan', 'KG', '🇰🇬'),
('laos', 'Laos', 'LA', '🇱🇦'),
('latvia', 'Latvia', 'LV', '🇱🇻'),
('lesotho', 'Lesotho', 'LS', '🇱🇸'),
('liberia', 'Liberia', 'LR', '🇱🇷'),
('lithuania', 'Lithuania', 'LT', '🇱🇹'),
('luxembourg', 'Luxembourg', 'LU', '🇱🇺'),
('macau', 'Macau', 'MO', '🇲🇴'),
('madagascar', 'Madagascar', 'MG', '🇲🇬'),
('malawi', 'Malawi', 'MW', '🇲🇼'),
('malaysia', 'Malaysia', 'MY', '🇲🇾'),
('maldives', 'Maldives', 'MV', '🇲🇻'),
('mauritania', 'Mauritania', 'MR', '🇲🇷'),
('mauritius', 'Mauritius', 'MU', '🇲🇺'),
('mexico', 'Mexico', 'MX', '🇲🇽'),
('moldova', 'Moldova', 'MD', '🇲🇩'),
('mongolia', 'Mongolia', 'MN', '🇲🇳'),
('montenegro', 'Montenegro', 'ME', '🇲🇪'),
('morocco', 'Morocco', 'MA', '🇲🇦'),
('mozambique', 'Mozambique', 'MZ', '🇲🇿'),
('namibia', 'Namibia', 'NA', '🇳🇦'),
('nepal', 'Nepal', 'NP', '🇳🇵'),
('netherlands', 'Netherlands', 'NL', '🇳🇱'),
('newcaledonia', 'New Caledonia', 'NC', '🇳🇨'),
('nicaragua', 'Nicaragua', 'NI', '🇳🇮'),
('nigeria', 'Nigeria', 'NG', '🇳🇬'),
('northmacedonia', 'North Macedonia', 'MK', '🇲🇰'),
('norway', 'Norway', 'NO', '🇳🇴'),
('oman', 'Oman', 'OM', '🇴🇲'),
('pakistan', 'Pakistan', 'PK', '🇵🇰'),
('panama', 'Panama', 'PA', '🇵🇦'),
('papuanewguinea', 'Papua New Guinea', 'PG', '🇵🇬'),
('paraguay', 'Paraguay', 'PY', '🇵🇾'),
('peru', 'Peru', 'PE', '🇵🇪'),
('philippines', 'Philippines', 'PH', '🇵🇭'),
('poland', 'Poland', 'PL', '🇵🇱'),
('portugal', 'Portugal', 'PT', '🇵🇹'),
('puertorico', 'Puerto Rico', 'PR', '🇵🇷'),
('reunion', 'Réunion', 'RE', '🇷🇪'),
('romania', 'Romania', 'RO', '🇷🇴'),
('rwanda', 'Rwanda', 'RW', '🇷🇼'),
('saintkittsandnevis', 'Saint Kitts & Nevis', 'KN', '🇰🇳'),
('saintlucia', 'Saint Lucia', 'LC', '🇱🇨'),
('saintvincentandgrenadines', 'Saint Vincent & Grenadines', 'VC', '🇻🇨'),
('salvador', 'El Salvador', 'SV', '🇸🇻'),
('samoa', 'Samoa', 'WS', '🇼🇸'),
('saudiarabia', 'Saudi Arabia', 'SA', '🇸🇦'),
('senegal', 'Senegal', 'SN', '🇸🇳'),
('serbia', 'Serbia', 'RS', '🇷🇸'),
('seychelles', 'Seychelles', 'SC', '🇸🇨'),
('sierraleone', 'Sierra Leone', 'SL', '🇸🇱'),
('slovakia', 'Slovakia', 'SK', '🇸🇰'),
('slovenia', 'Slovenia', 'SI', '🇸🇮'),
('solomonislands', 'Solomon Islands', 'SB', '🇸🇧'),
('southafrica', 'South Africa', 'ZA', '🇿🇦'),
('spain', 'Spain', 'ES', '🇪🇸'),
('srilanka', 'Sri Lanka', 'LK', '🇱🇰'),
('suriname', 'Suriname', 'SR', '🇸🇷'),
('swaziland', 'Eswatini', 'SZ', '🇸🇿'),
('sweden', 'Sweden', 'SE', '🇸🇪'),
('taiwan', 'Taiwan', 'TW', '🇹🇼'),
('tajikistan', 'Tajikistan', 'TJ', '🇹🇯'),
('tanzania', 'Tanzania', 'TZ', '🇹🇿'),
('thailand', 'Thailand', 'TH', '🇹🇭'),
('tit', 'Tit', 'XX', '🇽🇽'),
('togo', 'Togo', 'TG', '🇹🇬'),
('tunisia', 'Tunisia', 'TN', '🇹🇳'),
('turkmenistan', 'Turkmenistan', 'TM', '🇹🇲'),
('uganda', 'Uganda', 'UG', '🇺🇬'),
('ukraine', 'Ukraine', 'UA', '🇺🇦'),
('uruguay', 'Uruguay', 'UY', '🇺🇾'),
('usa', 'United States', 'US', '🇺🇸'),
('uzbekistan', 'Uzbekistan', 'UZ', '🇺🇿'),
('venezuela', 'Venezuela', 'VE', '🇻🇪'),
('vietnam', 'Vietnam', 'VN', '🇻🇳'),
('zambia', 'Zambia', 'ZM', '🇿🇲')
ON DUPLICATE KEY UPDATE
  `display_name` = VALUES(`display_name`),
  `iso2`         = VALUES(`iso2`),
  `flag`         = VALUES(`flag`),
  `updated_at`   = CURRENT_TIMESTAMP;
