package json

// JsonToolMeta holds metadata for each JSON tool
type JsonToolMeta struct {
	Key      string
	Icon     string
	Group    string
	TitleZH  string
	TitleEN  string
	DescZH   string
	DescEN   string
	Keywords string
}

// AllJsonToolMetas is the master list of all JSON tools
var AllJsonToolMetas = []JsonToolMeta{
	// Validate & Format
	{Key: "validate", Icon: "✅", Group: "validate", TitleZH: "JSON 验证器", TitleEN: "JSON Validator", DescZH: "在线验证 JSON 格式是否正确，实时高亮显示错误行号和位置，支持自动修复建议和语法检查，一键修复常见格式问题", DescEN: "Validate JSON format online with real-time error highlighting, line numbers, and auto-fix suggestions for common syntax issues", Keywords: "json validator, json lint, json checker, json verify, json syntax check"},
	{Key: "repair", Icon: "🔧", Group: "validate", TitleZH: "JSON 修复工具", TitleEN: "JSON Repair Tool", DescZH: "自动修复损坏的 JSON 数据，智能修复 LLM 输出错误、复制粘贴格式问题、单引号、尾随逗号、缺失括号等常见问题", DescEN: "Auto-fix broken JSON data from LLM outputs, copy-paste errors, single quotes, trailing commas, missing brackets and more", Keywords: "json repair, fix json, json fixer, fix broken json, json auto repair"},
	{Key: "pretty", Icon: "🎨", Group: "validate", TitleZH: "JSON 美化格式化", TitleEN: "JSON Pretty Print", DescZH: "在线格式化美化 JSON 数据，支持 2 空格、4 空格或 Tab 缩进，一键生成易读的树形结构，支持语法高亮", DescEN: "Format and beautify JSON data online with 2-space, 4-space or Tab indentation, generate readable tree structure with syntax highlighting", Keywords: "json formatter, json pretty print, json beautifier, format json online"},
	{Key: "minify", Icon: "⚡", Group: "validate", TitleZH: "JSON 压缩工具", TitleEN: "JSON Minify", DescZH: "在线压缩 JSON 数据，移除所有空白字符和换行符，最小化文件体积，提升网络传输效率，支持一键复制", DescEN: "Compress JSON data online by removing all whitespace and newlines to minimize file size, improve network transmission efficiency", Keywords: "json minify, json compress, json minifier, compress json online"},
	{Key: "sort-keys", Icon: "🔤", Group: "validate", TitleZH: "JSON Keys 排序", TitleEN: "Sort JSON Keys", DescZH: "递归排序 JSON 对象的所有 Key，支持字母升序或降序排列，方便对比和阅读，支持嵌套对象深度排序", DescEN: "Recursively sort all JSON object keys alphabetically in ascending or descending order, supports nested objects and deep sorting", Keywords: "json sort keys, json sort, alphabetical json, sort json object"},
	{Key: "escape", Icon: "🔒", Group: "validate", TitleZH: "JSON 转义工具", TitleEN: "JSON Escape", DescZH: "转义 JSON 字符串中的特殊字符，用于安全嵌入 HTML、JavaScript、Python 代码或 HTTP 请求，防止注入攻击", DescEN: "Escape special characters in JSON strings for safe embedding in HTML, JavaScript, Python code or HTTP requests, prevent injection attacks", Keywords: "json escape, escape json string, json encode"},
	{Key: "unescape", Icon: "🔓", Group: "validate", TitleZH: "JSON 反转义工具", TitleEN: "JSON Unescape", DescZH: "反转义 JSON 字符串，将转义字符还原为原始格式，恢复 Unicode 字符和特殊符号，还原可读性", DescEN: "Unescape JSON strings by converting escaped characters back to original format, restore Unicode and special symbols for readability", Keywords: "json unescape, unescape json, json decode"},
	{Key: "stringify", Icon: "📝", Group: "validate", TitleZH: "JSON Stringify", TitleEN: "JSON Stringify", DescZH: "将 JSON 对象转换为转义字符串格式，用于 JavaScript 程序传输、API 请求或本地存储，支持一键复制", DescEN: "Convert JSON object to escaped string format for JavaScript transmission, API requests or local storage with one-click copy", Keywords: "json stringify, json to string, json serialize"},
	// View & Query
	{Key: "tree", Icon: "🌳", Group: "view", TitleZH: "JSON 树形查看器", TitleEN: "JSON Tree Viewer", DescZH: "交互式树形可视化 JSON 数据，支持折叠/展开节点、搜索过滤、复制节点路径和值，深度解析嵌套结构", DescEN: "Interactive collapsible tree visualization for JSON data with expand/collapse nodes, search filter, copy path and values, deep parsing of nested structures", Keywords: "json tree viewer, json visualizer, json explorer, json tree structure"},
	{Key: "table", Icon: "📊", Group: "view", TitleZH: "JSON 表格查看器", TitleEN: "JSON Table Viewer", DescZH: "将 JSON 数组渲染为可排序可筛选的交互式表格，支持列排序、搜索、导出 CSV，方便数据浏览和分析", DescEN: "Display JSON arrays as interactive sortable and filterable tables with column sorting, search, CSV export for easy data browsing and analysis", Keywords: "json table, json to table, json grid, json array viewer"},
	{Key: "diff", Icon: "🔀", Group: "view", TitleZH: "JSON 对比工具", TitleEN: "JSON Diff", DescZH: "左右对比两个 JSON 对象，高亮显示差异部分，支持行级和节点级差异对比，快速定位数据变更", DescEN: "Compare two JSON objects side-by-side with diff highlighting, supports line-level and node-level difference comparison for quick data change detection", Keywords: "json diff, json compare, compare json, json difference"},
	{Key: "path", Icon: "🎯", Group: "view", TitleZH: "JSON Path 查询", TitleEN: "JSON Path", DescZH: "使用 JSONPath 表达式提取 JSON 数据，支持复杂路径查询、数组过滤、通配符匹配，快速定位嵌套数据", DescEN: "Query JSON data using JSONPath expressions with complex path queries, array filtering, wildcard matching for quick nested data extraction", Keywords: "jsonpath, json path, json query, json filter"},
	{Key: "search", Icon: "🔍", Group: "view", TitleZH: "JSON 搜索工具", TitleEN: "JSON Search", DescZH: "在 JSON 中搜索 Key 或 Value，支持文本搜索和正则表达式，快速查找数据，高亮显示匹配结果", DescEN: "Search for keys and values with text or regex search in JSON, quickly find data with highlighted match results", Keywords: "json search, search json, find in json, json text search"},
	{Key: "size", Icon: "📐", Group: "view", TitleZH: "JSON 大小分析", TitleEN: "JSON Size Analyzer", DescZH: "分析 JSON 数据大小、深度、节点数量、各字段占比和内存占用，生成详细的统计报告和可视化图表", DescEN: "Analyze JSON size, depth, node count, field distribution and memory usage with detailed statistics reports and visual charts", Keywords: "json size, json analyzer, json statistics, json data analysis"},
	{Key: "flatten", Icon: "📄", Group: "view", TitleZH: "JSON 扁平化工具", TitleEN: "JSON Flatten", DescZH: "将嵌套 JSON 转换为点号展开的扁平格式，或反向还原，支持自定义分隔符，方便数据处理和导入", DescEN: "Convert nested JSON to flat dot notation and back, supports custom separators for easy data processing and import", Keywords: "json flatten, flatten json, json unflatten, flat json"},
	// Data Converters
	{Key: "to-csv", Icon: "📋", Group: "convert", TitleZH: "JSON 转 CSV", TitleEN: "JSON to CSV", DescZH: "将 JSON 数组快速转换为 CSV 格式，自动处理嵌套对象和数组，支持自定义分隔符，可直接下载文件", DescEN: "Convert JSON arrays to CSV format quickly, automatically handle nested objects and arrays, supports custom delimiters with direct file download", Keywords: "json to csv, convert json csv, json array to csv, json csv export"},
	{Key: "from-csv", Icon: "📋", Group: "convert", TitleZH: "CSV 转 JSON", TitleEN: "CSV to JSON", DescZH: "将 CSV 文件解析为 JSON 格式，自动识别表头为 Key，支持自定义分隔符和编码，处理大数据文件", DescEN: "Parse CSV files into structured JSON format, automatically detect headers as keys, supports custom delimiters and encodings for large file processing", Keywords: "csv to json, csv converter, csv file to json, parse csv"},
	{Key: "to-excel", Icon: "📗", Group: "convert", TitleZH: "JSON 转 Excel", TitleEN: "JSON to Excel", DescZH: "将 JSON 数据导出为 Excel 电子表格（.xlsx），自动处理嵌套结构，支持多 Sheet 导出，格式化输出", DescEN: "Export JSON data to Excel spreadsheet (.xlsx), automatically handle nested structures, supports multi-sheet export with formatted output", Keywords: "json to excel, json xlsx, json export excel, json to xlsx"},
	{Key: "from-excel", Icon: "📗", Group: "convert", TitleZH: "Excel 转 JSON", TitleEN: "Excel to JSON", DescZH: "将 Excel 文件（.xlsx/.xls）转换为 JSON，自动识别表头，支持多 Sheet 处理，保留数据类型", DescEN: "Import Excel spreadsheet data as JSON, automatically detect headers, supports multi-sheet processing while preserving data types", Keywords: "excel to json, xlsx to json, excel converter, xls to json"},
	{Key: "to-yaml", Icon: "📑", Group: "convert", TitleZH: "JSON 转 YAML", TitleEN: "JSON to YAML", DescZH: "将 JSON 转换为 YAML 格式，自动处理缩进和引用，支持锚点和别名，生成易读的配置文件", DescEN: "Convert JSON to clean YAML format, automatically handle indentation and quoting, supports anchors and aliases for readable config files", Keywords: "json to yaml, convert json yaml, json yaml converter, yaml format"},
	{Key: "from-yaml", Icon: "📑", Group: "convert", TitleZH: "YAML 转 JSON", TitleEN: "YAML to JSON", DescZH: "将 YAML 配置文件解析为 JSON，支持 YAML 1.2 标准，处理多行字符串、列表和复杂结构", DescEN: "Parse YAML configuration files into JSON, supports YAML 1.2 standard, handles multi-line strings, lists and complex structures", Keywords: "yaml to json, yaml converter, yaml file to json, parse yaml"},
	{Key: "to-xml", Icon: "🏷️", Group: "convert", TitleZH: "JSON 转 XML", TitleEN: "JSON to XML", DescZH: "将 JSON 数据转换为 XML 结构，支持属性和命名空间，自定义根元素名称，兼容 SOAP 和 REST API", DescEN: "Transform JSON to XML structure, supports attributes and namespaces, custom root element names, compatible with SOAP and REST APIs", Keywords: "json to xml, convert json xml, json xml converter, xml generation"},
	{Key: "from-xml", Icon: "🏷️", Group: "convert", TitleZH: "XML 转 JSON", TitleEN: "XML to JSON", DescZH: "将 XML 文件解析为 JSON 结构，处理属性、CDATA 和命名空间，保留层级关系，支持大文件解析", DescEN: "Parse XML files into JSON structure, handles attributes, CDATA and namespaces, preserves hierarchy with large file support", Keywords: "xml to json, xml converter, xml file to json, parse xml"},
	{Key: "to-sql", Icon: "🗄️", Group: "convert", TitleZH: "JSON 转 SQL", TitleEN: "JSON to SQL", DescZH: "根据 JSON 数组生成 SQL INSERT 语句，支持多种数据库（MySQL/PostgreSQL/SQLite），自动转义字符", DescEN: "Generate SQL INSERT statements from JSON arrays, supports multiple databases (MySQL/PostgreSQL/SQLite) with automatic character escaping", Keywords: "json to sql, json sql insert, json database converter, sql generator"},
	{Key: "from-sql", Icon: "🗄️", Group: "convert", TitleZH: "SQL 转 JSON", TitleEN: "SQL to JSON", DescZH: "将 SQL 查询结果（DDL/INSERT）转换为 JSON 结构，自动解析表结构，支持复杂 SELECT 语句", DescEN: "Convert SQL query results (DDL/INSERT) to JSON structure, automatically parse table schemas, supports complex SELECT statements", Keywords: "sql to json, sql insert to json, sql converter, parse sql"},
	{Key: "to-markdown", Icon: "📖", Group: "convert", TitleZH: "JSON 转 Markdown", TitleEN: "JSON to Markdown", DescZH: "将 JSON 数组生成 Markdown 表格，支持 GitHub Flavored Markdown，自动对齐列，可复制到文档", DescEN: "Generate Markdown tables from JSON arrays, supports GitHub Flavored Markdown, automatically aligns columns for easy copying to documents", Keywords: "json to markdown, json table markdown, markdown table generator"},
	// Code Generators
	{Key: "to-typescript", Icon: "🔷", Group: "codegen", TitleZH: "JSON 转 TypeScript", TitleEN: "JSON to TypeScript", DescZH: "根据 JSON 自动生成 TypeScript interface 定义，支持嵌套对象、可选字段和联合类型，生成 JSDoc 注释", DescEN: "Generate TypeScript interfaces from JSON data, supports nested objects, optional fields and union types with JSDoc comments", Keywords: "json to typescript, json typescript interface, ts interface generator"},
	{Key: "to-python", Icon: "🐍", Group: "codegen", TitleZH: "JSON 转 Python", TitleEN: "JSON to Python", DescZH: "根据 JSON 生成 Python dataclass，支持类型注解、默认值和嵌套类，兼容 Pydantic 模型", DescEN: "Generate Python dataclasses from JSON with type annotations, default values and nested classes, compatible with Pydantic models", Keywords: "json to python, json python dataclass, python class generator"},
	{Key: "to-java", Icon: "☕", Group: "codegen", TitleZH: "JSON 转 Java", TitleEN: "JSON to Java", DescZH: "根据 JSON 生成 Java POJO 类，支持 Getter/Setter、构造函数和 Jackson/Gson 注解", DescEN: "Generate Java POJO classes from JSON with Getters/Setters, constructors and Jackson/Gson annotations", Keywords: "json to java, json java class pojo, java class generator"},
	{Key: "to-csharp", Icon: "💠", Group: "codegen", TitleZH: "JSON 转 C#", TitleEN: "JSON to C#", DescZH: "根据 JSON 生成 C# class 定义，支持属性特性、JSON.NET 序列化和 DataAnnotations", DescEN: "Generate C# classes from JSON with property attributes, JSON.NET serialization and DataAnnotations", Keywords: "json to csharp, json c# class, csharp class generator"},
	{Key: "to-go", Icon: "🐹", Group: "codegen", TitleZH: "JSON 转 Go", TitleEN: "JSON to Go", DescZH: "根据 JSON 生成 Go struct 定义，支持 JSON 标签、omitempty 和指针类型", DescEN: "Generate Go structs from JSON with JSON tags, omitempty and pointer types", Keywords: "json to go, json golang struct, go struct generator"},
	{Key: "to-kotlin", Icon: "🎯", Group: "codegen", TitleZH: "JSON 转 Kotlin", TitleEN: "JSON to Kotlin", DescZH: "根据 JSON 生成 Kotlin data class，支持 @Serializable 注解和可选参数", DescEN: "Generate Kotlin data classes from JSON with @Serializable annotations and optional parameters", Keywords: "json to kotlin, json kotlin data class, kotlin class generator"},
	{Key: "to-swift", Icon: "🍎", Group: "codegen", TitleZH: "JSON 转 Swift", TitleEN: "JSON to Swift", DescZH: "根据 JSON 生成 Swift Codable struct，支持 Decodable/Encodable 协议和自定义 CodingKeys", DescEN: "Generate Swift Codable structs from JSON with Decodable/Encodable protocols and custom CodingKeys", Keywords: "json to swift, json swift codable, swift struct generator"},
	{Key: "to-rust", Icon: "🦀", Group: "codegen", TitleZH: "JSON 转 Rust", TitleEN: "JSON to Rust", DescZH: "根据 JSON 生成 Rust serde struct，支持 Serialize/Deserialize trait 和别名", DescEN: "Generate Rust structs with serde from JSON, supports Serialize/Deserialize traits and aliases", Keywords: "json to rust, json rust serde, rust struct generator"},
	{Key: "to-php", Icon: "🐘", Group: "codegen", TitleZH: "JSON 转 PHP", TitleEN: "JSON to PHP", DescZH: "根据 JSON 生成 PHP class 定义，支持类型属性和 JSON 序列化注解", DescEN: "Generate PHP classes from JSON with typed properties and JSON serialization annotations", Keywords: "json to php, json php class, php class generator"},
	// Schema
	{Key: "schema-validate", Icon: "🛡️", Group: "schema", TitleZH: "JSON Schema 验证", TitleEN: "JSON Schema Validator", DescZH: "根据 JSON Schema 验证 JSON 数据合法性，支持 Draft-2020-12 标准，显示详细错误信息和路径", DescEN: "Validate JSON data against JSON Schema, supports Draft-2020-12 standard with detailed error messages and paths", Keywords: "json schema validator, jsonschema, schema validation"},
	{Key: "schema-generate", Icon: "🏗️", Group: "schema", TitleZH: "JSON Schema 生成", TitleEN: "JSON Schema Generator", DescZH: "根据 JSON 数据自动推断生成 JSON Schema，支持类型推断、必需字段和默认值设置", DescEN: "Auto-generate JSON Schema from sample data with type inference, required fields and default values", Keywords: "json schema generator, generate schema, schema inference"},
	// Encoding
	{Key: "base64", Icon: "🔐", Group: "encode", TitleZH: "Base64 编解码", TitleEN: "Base64 Encode/Decode", DescZH: "对 JSON 数据进行 Base64 编码或解码，支持 UTF-8 字符集，用于安全传输和存储", DescEN: "Encode or decode JSON as Base64 with UTF-8 charset for secure transmission and storage", Keywords: "json base64, base64 encode decode, base64 converter"},
	{Key: "jwt", Icon: "🎫", Group: "encode", TitleZH: "JWT 解码工具", TitleEN: "JWT Decoder", DescZH: "解析 JWT Token，查看 Header、Payload 和 Signature，验证签名算法和过期时间，支持调试", DescEN: "Decode and inspect JWT token Header, Payload and Signature, verify signature algorithm and expiration for debugging", Keywords: "jwt decoder, jwt parser, decode jwt, jwt token debug"},
	{Key: "jsonc", Icon: "💬", Group: "encode", TitleZH: "JSONC 转 JSON", TitleEN: "JSONC to JSON", DescZH: "移除 JSONC/JSON5 文件中的注释和尾随逗号，转为标准 JSON 格式，支持 VSCode 配置文件", DescEN: "Strip comments from JSONC/JSON5 files, convert to standard JSON format, supports VSCode config files", Keywords: "jsonc to json, json5, json comments, json5 parser"},
	{Key: "token-count", Icon: "🔢", Group: "encode", TitleZH: "Token 计数工具", TitleEN: "Token Counter", DescZH: "统计 GPT-4、Claude、Gemini 等 LLM 模型的 Token 数量，估算 API 调用成本，支持多种分词器", DescEN: "Count tokens for GPT-4, Claude, Gemini and other LLMs, estimate API call costs with multiple tokenizer support", Keywords: "token counter, gpt token count, llm tokens, token calculator"},
	// Generate & Transform
	{Key: "json-generator", Icon: "🎲", Group: "generate", TitleZH: "JSON 随机生成器", TitleEN: "JSON Generator", DescZH: "根据 Schema 或模板生成随机 JSON 测试数据，支持多种数据类型和约束，用于单元测试和模拟", DescEN: "Generate random JSON test data from schema or template, supports multiple data types and constraints for unit testing and mocking", Keywords: "json generator, random json, mock data, json faker"},
	{Key: "to-query", Icon: "🔗", Group: "generate", TitleZH: "JSON 转 URL 参数", TitleEN: "JSON to URL Query", DescZH: "将 JSON 对象转换为 URL 查询字符串参数，自动编码特殊字符，支持 GET 请求参数构建", DescEN: "Convert JSON object to URL query string parameters, automatically encode special characters for GET request construction", Keywords: "json to query, json to url, query string, url params"},
	{Key: "from-query", Icon: "🔗", Group: "generate", TitleZH: "URL 参数转 JSON", TitleEN: "URL Query to JSON", DescZH: "将 URL 查询字符串解析为 JSON 对象，自动解码参数值，支持数组参数解析", DescEN: "Parse URL query string to JSON object, automatically decode parameter values, supports array parameter parsing", Keywords: "query to json, url to json, parse query, query string parser"},
	{Key: "python-dict", Icon: "🐍", Group: "generate", TitleZH: "Python Dict 转换", TitleEN: "Python Dict Converter", DescZH: "Python 字典格式与 JSON 互转，自动处理单引号双引号、True/False 和 None/null", DescEN: "Convert between Python dict and JSON format, automatically handle single/double quotes, True/False and None/null", Keywords: "python dict to json, dict converter, python json"},
	// TOML Converter
	{Key: "to-toml", Icon: "📝", Group: "convert", TitleZH: "JSON 转 TOML", TitleEN: "JSON to TOML", DescZH: "将 JSON 转换为 TOML 配置格式，自动处理数组、表格和嵌套结构，适用于 Cargo 和 Rust 配置", DescEN: "Convert JSON to TOML configuration format, automatically handle arrays, tables and nested structures, suitable for Cargo and Rust config", Keywords: "json to toml, toml converter, toml config, cargo toml"},
	{Key: "from-toml", Icon: "📝", Group: "convert", TitleZH: "TOML 转 JSON", TitleEN: "TOML to JSON", DescZH: "将 TOML 配置文件解析为 JSON，支持数组、表格、日期时间类型，兼容 TOML 1.0 标准", DescEN: "Parse TOML configuration to JSON, supports arrays, tables, datetime types, compatible with TOML 1.0 standard", Keywords: "toml to json, parse toml, toml parser, toml file"},
	// Additional Code Generators
	{Key: "to-dart", Icon: "🎯", Group: "codegen", TitleZH: "JSON 转 Dart", TitleEN: "JSON to Dart", DescZH: "根据 JSON 生成 Dart 类，支持 Flutter 开发，支持 json_serializable 注解和 Freezed", DescEN: "Generate Dart classes from JSON for Flutter, supports json_serializable annotations and Freezed", Keywords: "json to dart, dart class, flutter json, dart model"},
	{Key: "to-objc", Icon: "🍎", Group: "codegen", TitleZH: "JSON 转 Objective-C", TitleEN: "JSON to Objective-C", DescZH: "根据 JSON 生成 Objective-C 模型类，支持 NSDictionary 和 NSArray 映射，兼容 iOS 开发", DescEN: "Generate Objective-C model classes from JSON, supports NSDictionary and NSArray mapping, compatible with iOS development", Keywords: "json to objective-c, objc model, ios json, nsdictionary"},
	{Key: "to-cpp", Icon: "⚙️", Group: "codegen", TitleZH: "JSON 转 C++", TitleEN: "JSON to C++", DescZH: "根据 JSON 生成 C++ 结构体定义，支持 nlohmann/json 和 RapidJSON，支持命名空间", DescEN: "Generate C++ structs from JSON, supports nlohmann/json and RapidJSON with namespaces", Keywords: "json to cpp, c++ struct, cpp json, c++ class generator"},
	{Key: "to-ruby", Icon: "💎", Group: "codegen", TitleZH: "JSON 转 Ruby", TitleEN: "JSON to Ruby", DescZH: "根据 JSON 生成 Ruby 类或 Struct，支持 attr_reader 和类型定义，兼容 Rails", DescEN: "Generate Ruby classes or structs from JSON, supports attr_reader and type definitions, compatible with Rails", Keywords: "json to ruby, ruby class, rails json, ruby struct"},
	{Key: "to-scala", Icon: "☕", Group: "codegen", TitleZH: "JSON 转 Scala", TitleEN: "JSON to Scala", DescZH: "根据 JSON 生成 Scala case class，支持 Play JSON 和 Circe 序列化", DescEN: "Generate Scala case classes from JSON, supports Play JSON and Circe serialization", Keywords: "json to scala, scala case class, play json, circe"},
	{Key: "highlight-export", Icon: "🎨", Group: "encode", TitleZH: "JSON 着色导出", TitleEN: "JSON Highlight Export", DescZH: "将 JSON 导出为带语法高亮的 HTML 或 RTF 文件，支持自定义主题，用于文档展示", DescEN: "Export JSON with syntax highlighting as HTML or RTF, supports custom themes for documentation display", Keywords: "json highlight, json export, syntax highlighting, json to html"},
	// New Tools — Generate & Transform
	{Key: "jsonl", Icon: "📜", Group: "convert", TitleZH: "JSONL 工具", TitleEN: "JSONL Tools", DescZH: "JSONL 格式化、验证，支持 JSONL 与 JSON Array 互转，适用于大文件和日志处理", DescEN: "Format, validate, and convert between JSONL and JSON Array, suitable for large files and log processing", Keywords: "jsonl, json lines, ndjson, jsonl to json"},
	{Key: "merge", Icon: "🔗", Group: "generate", TitleZH: "JSON 合并工具", TitleEN: "JSON Merge", DescZH: "合并多个 JSON 对象，支持浅合并和深合并策略，处理冲突和数组合并", DescEN: "Merge multiple JSON objects with shallow or deep merge strategies, handles conflicts and array merging", Keywords: "json merge, merge json, deep merge, combine json"},
	{Key: "transform", Icon: "🔄", Group: "generate", TitleZH: "JSON 变换工具", TitleEN: "JSON Transform", DescZH: "使用 jq 风格表达式过滤、映射、变换 JSON 数据，支持复杂的数据处理逻辑", DescEN: "Transform JSON with jq-style filter, map, and select expressions for complex data processing logic", Keywords: "json transform, jq, json filter, json map"},
	{Key: "patch", Icon: "🩹", Group: "generate", TitleZH: "JSON Patch", TitleEN: "JSON Patch", DescZH: "RFC 6902 JSON Patch 操作，支持 add/remove/replace/move/copy/test 操作", DescEN: "Apply RFC 6902 JSON Patch operations: add, remove, replace, move, copy and test", Keywords: "json patch, rfc 6902, json diff patch, patch json"},
	{Key: "mock", Icon: "🎲", Group: "generate", TitleZH: "JSON Mock 生成", TitleEN: "JSON Mock Generator", DescZH: "根据 JSON Schema 生成随机模拟数据，支持 faker 库生成真实姓名、邮箱、地址等", DescEN: "Generate random mock data from JSON Schema, supports faker library for realistic names, emails, addresses and more", Keywords: "json mock, mock data generator, fake data, json faker"},
	{Key: "to-zod", Icon: "🛡️", Group: "codegen", TitleZH: "JSON 转 Zod", TitleEN: "JSON to Zod", DescZH: "根据 JSON 生成 TypeScript Zod Schema，支持运行时验证和类型推断", DescEN: "Generate TypeScript Zod schemas from JSON data with runtime validation and type inference", Keywords: "json to zod, zod schema, typescript validation, zod generator"},
	{Key: "to-graphql", Icon: "🔷", Group: "codegen", TitleZH: "JSON 转 GraphQL", TitleEN: "JSON to GraphQL", DescZH: "根据 JSON 生成 GraphQL Type 定义，支持输入类型和查询类型，适用于 Apollo 和 Relay", DescEN: "Generate GraphQL type definitions from JSON, supports input and query types for Apollo and Relay", Keywords: "json to graphql, graphql schema, graphql type, graphql generator"},
	{Key: "to-env", Icon: "⚙️", Group: "generate", TitleZH: "JSON 转 .env", TitleEN: "JSON to .env", DescZH: "将扁平化 JSON 转换为 KEY=VALUE 格式的 .env 文件，支持环境变量管理", DescEN: "Convert flat JSON to KEY=VALUE .env format for environment variable management", Keywords: "json to env, env file, environment variables, .env generator"},
	{Key: "redact", Icon: "🔒", Group: "generate", TitleZH: "JSON 脱敏工具", TitleEN: "JSON Redact", DescZH: "自动检测并脱敏 JSON 中的敏感数据，如邮箱、手机号、身份证号、信用卡号等", DescEN: "Auto-detect and redact sensitive data in JSON including emails, phone numbers, IDs and credit card numbers", Keywords: "json redact, data masking, json anonymize, pii removal"},
	{Key: "array", Icon: "📊", Group: "generate", TitleZH: "JSON 数组工具", TitleEN: "JSON Array Utils", DescZH: "JSON 数组操作工具，支持排序、去重、分块、打乱、分组、过滤等常见操作", DescEN: "Sort, deduplicate, chunk, shuffle, group and filter JSON arrays with common operations", Keywords: "json array sort, deduplicate, chunk, group by, array utils"},
	{Key: "key-transform", Icon: "🔤", Group: "generate", TitleZH: "JSON Key 转换", TitleEN: "JSON Key Transformer", DescZH: "批量转换 JSON Key 命名格式，支持 camelCase、snake_case、PascalCase、kebab-case 互转", DescEN: "Batch convert JSON keys between camelCase, snake_case, PascalCase and kebab-case formats", Keywords: "json key transform, camelcase to snake_case, key case converter, naming convention"},
}
